---
- name: Ensure required Python libraries are installed
  pip:
    name:
      - google-auth
      - requests
      - google-cloud-compute
    state: present

- name: Create application directory
  file:
    path: /opt/{{ app_name }}
    state: directory
    mode: "0755"

- name: Deploy Python application
  template:
    src: app.py.j2
    dest: /opt/{{ app_name }}/app.py
    mode: "0644"

- name: Create systemd service
  template:
    src: app.service.j2
    dest: /etc/systemd/system/{{ app_name }}.service
    mode: "0644"
  notify: restart app

- name: Enable and start application service
  systemd:
    name: "{{ app_name }}"
    enabled: yes
    state: started
